# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - selenium-demo-examples

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: Set up Node.js version 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: npm install
      run: |
        cd examples
        npm install

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'selenium-demo'
        slot-name: 'PRODUCTION'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_624ef1c330424f04aaab22bf3b58b2a5 }}
        package: ./examples
